// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: recordbudget.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordBudgetService_AddBudget_FullMethodName  = "/recordbudget.RecordBudgetService/AddBudget"
	RecordBudgetService_SeedBudget_FullMethodName = "/recordbudget.RecordBudgetService/SeedBudget"
	RecordBudgetService_GetBudget_FullMethodName  = "/recordbudget.RecordBudgetService/GetBudget"
	RecordBudgetService_GetSold_FullMethodName    = "/recordbudget.RecordBudgetService/GetSold"
	RecordBudgetService_GetOrders_FullMethodName  = "/recordbudget.RecordBudgetService/GetOrders"
)

// RecordBudgetServiceClient is the client API for RecordBudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordBudgetServiceClient interface {
	AddBudget(ctx context.Context, in *AddBudgetRequest, opts ...grpc.CallOption) (*AddBudgetResponse, error)
	SeedBudget(ctx context.Context, in *SeedBudgetRequest, opts ...grpc.CallOption) (*SeedBudgetResponse, error)
	GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error)
	GetSold(ctx context.Context, in *GetSoldRequest, opts ...grpc.CallOption) (*GetSoldResponse, error)
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
}

type recordBudgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordBudgetServiceClient(cc grpc.ClientConnInterface) RecordBudgetServiceClient {
	return &recordBudgetServiceClient{cc}
}

func (c *recordBudgetServiceClient) AddBudget(ctx context.Context, in *AddBudgetRequest, opts ...grpc.CallOption) (*AddBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBudgetResponse)
	err := c.cc.Invoke(ctx, RecordBudgetService_AddBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordBudgetServiceClient) SeedBudget(ctx context.Context, in *SeedBudgetRequest, opts ...grpc.CallOption) (*SeedBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedBudgetResponse)
	err := c.cc.Invoke(ctx, RecordBudgetService_SeedBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordBudgetServiceClient) GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetResponse)
	err := c.cc.Invoke(ctx, RecordBudgetService_GetBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordBudgetServiceClient) GetSold(ctx context.Context, in *GetSoldRequest, opts ...grpc.CallOption) (*GetSoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSoldResponse)
	err := c.cc.Invoke(ctx, RecordBudgetService_GetSold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordBudgetServiceClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, RecordBudgetService_GetOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordBudgetServiceServer is the server API for RecordBudgetService service.
// All implementations should embed UnimplementedRecordBudgetServiceServer
// for forward compatibility.
type RecordBudgetServiceServer interface {
	AddBudget(context.Context, *AddBudgetRequest) (*AddBudgetResponse, error)
	SeedBudget(context.Context, *SeedBudgetRequest) (*SeedBudgetResponse, error)
	GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error)
	GetSold(context.Context, *GetSoldRequest) (*GetSoldResponse, error)
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
}

// UnimplementedRecordBudgetServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordBudgetServiceServer struct{}

func (UnimplementedRecordBudgetServiceServer) AddBudget(context.Context, *AddBudgetRequest) (*AddBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBudget not implemented")
}
func (UnimplementedRecordBudgetServiceServer) SeedBudget(context.Context, *SeedBudgetRequest) (*SeedBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeedBudget not implemented")
}
func (UnimplementedRecordBudgetServiceServer) GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudget not implemented")
}
func (UnimplementedRecordBudgetServiceServer) GetSold(context.Context, *GetSoldRequest) (*GetSoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSold not implemented")
}
func (UnimplementedRecordBudgetServiceServer) GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedRecordBudgetServiceServer) testEmbeddedByValue() {}

// UnsafeRecordBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordBudgetServiceServer will
// result in compilation errors.
type UnsafeRecordBudgetServiceServer interface {
	mustEmbedUnimplementedRecordBudgetServiceServer()
}

func RegisterRecordBudgetServiceServer(s grpc.ServiceRegistrar, srv RecordBudgetServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecordBudgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordBudgetService_ServiceDesc, srv)
}

func _RecordBudgetService_AddBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).AddBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordBudgetService_AddBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).AddBudget(ctx, req.(*AddBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordBudgetService_SeedBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).SeedBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordBudgetService_SeedBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).SeedBudget(ctx, req.(*SeedBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordBudgetService_GetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).GetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordBudgetService_GetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).GetBudget(ctx, req.(*GetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordBudgetService_GetSold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).GetSold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordBudgetService_GetSold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).GetSold(ctx, req.(*GetSoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordBudgetService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordBudgetService_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordBudgetService_ServiceDesc is the grpc.ServiceDesc for RecordBudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordBudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recordbudget.RecordBudgetService",
	HandlerType: (*RecordBudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBudget",
			Handler:    _RecordBudgetService_AddBudget_Handler,
		},
		{
			MethodName: "SeedBudget",
			Handler:    _RecordBudgetService_SeedBudget_Handler,
		},
		{
			MethodName: "GetBudget",
			Handler:    _RecordBudgetService_GetBudget_Handler,
		},
		{
			MethodName: "GetSold",
			Handler:    _RecordBudgetService_GetSold_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _RecordBudgetService_GetOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordbudget.proto",
}
