// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordbudget.proto

package recordbudget

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastRecordcollectionPull int64              `protobuf:"varint,1,opt,name=last_recordcollection_pull,json=lastRecordcollectionPull,proto3" json:"last_recordcollection_pull,omitempty"`
	Purchases                []*BoughtRecord    `protobuf:"bytes,2,rep,name=purchases,proto3" json:"purchases,omitempty"`
	PrePurchases             []*PreBoughtRecord `protobuf:"bytes,3,rep,name=pre_purchases,json=prePurchases,proto3" json:"pre_purchases,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}           `json:"-"`
	XXX_unrecognized         []byte             `json:"-"`
	XXX_sizecache            int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_061dd85d90c17150, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastRecordcollectionPull() int64 {
	if m != nil {
		return m.LastRecordcollectionPull
	}
	return 0
}

func (m *Config) GetPurchases() []*BoughtRecord {
	if m != nil {
		return m.Purchases
	}
	return nil
}

func (m *Config) GetPrePurchases() []*PreBoughtRecord {
	if m != nil {
		return m.PrePurchases
	}
	return nil
}

type BoughtRecord struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cost                 int32    `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	BoughtDate           int64    `protobuf:"varint,3,opt,name=bought_date,json=boughtDate,proto3" json:"bought_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoughtRecord) Reset()         { *m = BoughtRecord{} }
func (m *BoughtRecord) String() string { return proto.CompactTextString(m) }
func (*BoughtRecord) ProtoMessage()    {}
func (*BoughtRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_061dd85d90c17150, []int{1}
}

func (m *BoughtRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoughtRecord.Unmarshal(m, b)
}
func (m *BoughtRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoughtRecord.Marshal(b, m, deterministic)
}
func (m *BoughtRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoughtRecord.Merge(m, src)
}
func (m *BoughtRecord) XXX_Size() int {
	return xxx_messageInfo_BoughtRecord.Size(m)
}
func (m *BoughtRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BoughtRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BoughtRecord proto.InternalMessageInfo

func (m *BoughtRecord) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *BoughtRecord) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *BoughtRecord) GetBoughtDate() int64 {
	if m != nil {
		return m.BoughtDate
	}
	return 0
}

type PreBoughtRecord struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cost                 int32    `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreBoughtRecord) Reset()         { *m = PreBoughtRecord{} }
func (m *PreBoughtRecord) String() string { return proto.CompactTextString(m) }
func (*PreBoughtRecord) ProtoMessage()    {}
func (*PreBoughtRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_061dd85d90c17150, []int{2}
}

func (m *PreBoughtRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreBoughtRecord.Unmarshal(m, b)
}
func (m *PreBoughtRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreBoughtRecord.Marshal(b, m, deterministic)
}
func (m *PreBoughtRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreBoughtRecord.Merge(m, src)
}
func (m *PreBoughtRecord) XXX_Size() int {
	return xxx_messageInfo_PreBoughtRecord.Size(m)
}
func (m *PreBoughtRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PreBoughtRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PreBoughtRecord proto.InternalMessageInfo

func (m *PreBoughtRecord) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PreBoughtRecord) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type GetBudgetRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBudgetRequest) Reset()         { *m = GetBudgetRequest{} }
func (m *GetBudgetRequest) String() string { return proto.CompactTextString(m) }
func (*GetBudgetRequest) ProtoMessage()    {}
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_061dd85d90c17150, []int{3}
}

func (m *GetBudgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBudgetRequest.Unmarshal(m, b)
}
func (m *GetBudgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBudgetRequest.Marshal(b, m, deterministic)
}
func (m *GetBudgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBudgetRequest.Merge(m, src)
}
func (m *GetBudgetRequest) XXX_Size() int {
	return xxx_messageInfo_GetBudgetRequest.Size(m)
}
func (m *GetBudgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBudgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBudgetRequest proto.InternalMessageInfo

func (m *GetBudgetRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type GetBudgetResponse struct {
	Spends               int32    `protobuf:"varint,1,opt,name=spends,proto3" json:"spends,omitempty"`
	Budget               int32    `protobuf:"varint,2,opt,name=budget,proto3" json:"budget,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBudgetResponse) Reset()         { *m = GetBudgetResponse{} }
func (m *GetBudgetResponse) String() string { return proto.CompactTextString(m) }
func (*GetBudgetResponse) ProtoMessage()    {}
func (*GetBudgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_061dd85d90c17150, []int{4}
}

func (m *GetBudgetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBudgetResponse.Unmarshal(m, b)
}
func (m *GetBudgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBudgetResponse.Marshal(b, m, deterministic)
}
func (m *GetBudgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBudgetResponse.Merge(m, src)
}
func (m *GetBudgetResponse) XXX_Size() int {
	return xxx_messageInfo_GetBudgetResponse.Size(m)
}
func (m *GetBudgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBudgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBudgetResponse proto.InternalMessageInfo

func (m *GetBudgetResponse) GetSpends() int32 {
	if m != nil {
		return m.Spends
	}
	return 0
}

func (m *GetBudgetResponse) GetBudget() int32 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "recordbudget.Config")
	proto.RegisterType((*BoughtRecord)(nil), "recordbudget.BoughtRecord")
	proto.RegisterType((*PreBoughtRecord)(nil), "recordbudget.PreBoughtRecord")
	proto.RegisterType((*GetBudgetRequest)(nil), "recordbudget.GetBudgetRequest")
	proto.RegisterType((*GetBudgetResponse)(nil), "recordbudget.GetBudgetResponse")
}

func init() { proto.RegisterFile("recordbudget.proto", fileDescriptor_061dd85d90c17150) }

var fileDescriptor_061dd85d90c17150 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0x76, 0xad, 0x0e, 0x76, 0x36, 0xff, 0x8e, 0x20, 0x65, 0xa0, 0x1b, 0xbd, 0x90, 0x5d, 0xed,
	0x62, 0x22, 0x78, 0xe1, 0xd5, 0x26, 0x88, 0x37, 0x32, 0xea, 0x03, 0x94, 0x2e, 0x39, 0x6e, 0x85,
	0xd0, 0xc4, 0x24, 0x15, 0x7c, 0x3f, 0x1f, 0x4c, 0x9a, 0x66, 0x3f, 0x2d, 0x7a, 0x97, 0x7c, 0x7f,
	0xf9, 0xce, 0x21, 0x80, 0x9a, 0x98, 0xd4, 0x7c, 0x55, 0xf2, 0x35, 0xd9, 0xa9, 0xd2, 0xd2, 0x4a,
	0x1c, 0x1c, 0x62, 0xf1, 0x4f, 0x07, 0xba, 0x0b, 0x59, 0x7c, 0xe4, 0x6b, 0x7c, 0x82, 0xa1, 0xc8,
	0x8c, 0x4d, 0x6b, 0x9e, 0x49, 0x21, 0x88, 0xd9, 0x5c, 0x16, 0xa9, 0x2a, 0x85, 0x88, 0x3a, 0xe3,
	0xce, 0x24, 0x4c, 0xa2, 0x4a, 0x91, 0xb4, 0x04, 0xcb, 0x52, 0x08, 0x7c, 0x84, 0x9e, 0x2a, 0x35,
	0xdb, 0x64, 0x86, 0x4c, 0x14, 0x8c, 0xc3, 0x49, 0x7f, 0x36, 0x9c, 0x36, 0x9e, 0x9f, 0xcb, 0x72,
	0xbd, 0xf1, 0xe6, 0x64, 0x2f, 0xc6, 0x39, 0x9c, 0x2a, 0x4d, 0xe9, 0xde, 0x1d, 0x3a, 0xf7, 0x4d,
	0xd3, 0xbd, 0xd4, 0xd4, 0x08, 0x18, 0x28, 0x4d, 0xcb, 0xad, 0x25, 0xe6, 0x30, 0x38, 0x64, 0x71,
	0x04, 0xfd, 0xbc, 0x30, 0x36, 0x2b, 0x18, 0xa5, 0x39, 0x77, 0xe5, 0x4f, 0x12, 0xd8, 0x42, 0xaf,
	0x1c, 0x11, 0x8e, 0x99, 0x34, 0x36, 0x0a, 0x1c, 0xe3, 0xce, 0x95, 0x69, 0xe5, 0x42, 0x52, 0x9e,
	0x59, 0x8a, 0x42, 0x37, 0x31, 0xd4, 0xd0, 0x73, 0x66, 0x29, 0x7e, 0x80, 0xf3, 0x56, 0x0d, 0x3c,
	0x83, 0x60, 0x97, 0x1f, 0xe4, 0x7f, 0xe6, 0xc6, 0x77, 0x70, 0xf1, 0x42, 0x76, 0xee, 0xe6, 0x48,
	0xe8, 0xb3, 0x24, 0x63, 0x2b, 0xdd, 0x37, 0x65, 0xda, 0x3b, 0xdd, 0x39, 0x5e, 0xc0, 0xe5, 0x81,
	0xce, 0x28, 0x59, 0x18, 0xc2, 0x6b, 0xe8, 0x1a, 0x45, 0x05, 0x37, 0x5e, 0xea, 0x6f, 0x15, 0x5e,
	0x6f, 0xc6, 0x3f, 0xe5, 0x6f, 0x33, 0x82, 0xab, 0xba, 0x5a, 0x9d, 0xf3, 0x4e, 0xfa, 0x2b, 0x67,
	0x84, 0x6f, 0xd0, 0xdb, 0x65, 0xe3, 0x6d, 0x73, 0xb5, 0xed, 0x72, 0xc3, 0xd1, 0xbf, 0x7c, 0x5d,
	0x2a, 0x3e, 0x5a, 0x75, 0xdd, 0x67, 0xba, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x92, 0x77, 0x41,
	0xe4, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordBudgetServiceClient is the client API for RecordBudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordBudgetServiceClient interface {
	GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error)
}

type recordBudgetServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecordBudgetServiceClient(cc *grpc.ClientConn) RecordBudgetServiceClient {
	return &recordBudgetServiceClient{cc}
}

func (c *recordBudgetServiceClient) GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error) {
	out := new(GetBudgetResponse)
	err := c.cc.Invoke(ctx, "/recordbudget.RecordBudgetService/GetBudget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordBudgetServiceServer is the server API for RecordBudgetService service.
type RecordBudgetServiceServer interface {
	GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error)
}

func RegisterRecordBudgetServiceServer(s *grpc.Server, srv RecordBudgetServiceServer) {
	s.RegisterService(&_RecordBudgetService_serviceDesc, srv)
}

func _RecordBudgetService_GetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordBudgetServiceServer).GetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordbudget.RecordBudgetService/GetBudget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordBudgetServiceServer).GetBudget(ctx, req.(*GetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordBudgetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordbudget.RecordBudgetService",
	HandlerType: (*RecordBudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBudget",
			Handler:    _RecordBudgetService_GetBudget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordbudget.proto",
}
